#DATASOURCE H2
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:library
    username: root
    password: root
  jpa:
    database-plataform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

#H2 CONSOLE
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
